# Generated by Django 3.1.6 on 2021-05-26 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('content', models.CharField(max_length=500)),
                ('post_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=200)),
                ('user_password', models.CharField(max_length=200)),
                ('user_dob', models.DateTimeField(default='')),
                ('user_create_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_content', models.CharField(max_length=500)),
                ('com_board_url', models.CharField(max_length=500)),
                ('com_create_date', models.DateTimeField(auto_now_add=True)),
                ('post_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='k8s_doc.post')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='k8s_doc.user')),
            ],
        ),
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_board_url', models.CharField(max_length=500)),
                ('book_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='k8s_doc.user')),
            ],
        ),
    ]
