# Generated by Django 3.1.6 on 2021-06-01 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('k8s_doc', '0002_auto_20210531_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(max_length=5000),
        ),
    ]
