# Generated by Django 3.1.6 on 2021-06-02 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('k8s_doc', '0003_auto_20210601_1240'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookmark',
            name='book_board_url',
        ),
        migrations.AddField(
            model_name='bookmark',
            name='post_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='k8s_doc.post'),
        ),
    ]
